version: '3.9'
services:
   svelte:
    restart: always
    image: ollami-svelte
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    extra_hosts:
      - host.docker.internal:host-gateway
