version: "3.9"
services:
  ollami:
    container_name: app
    restart: always
    image: ollami
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5050:5050
  
  chroma:
    container_name: chroma
    restart: always
    image: chromadb/chroma
    ports:
      - 8000:8000
